# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f31ef8fbdb537dae3efbbe0807162255c3e3f236e4d125de4848cb8b734ce950e841621d71bb15bcb2d34396ee155a237594712d649dd4910f2f72ade9d0bad

test:
  secret_key_base: 46caa496840f8829049d638d77600709b20c6b0807563ad48a8705767dd355341c4841bba6afbc65e65992ab08b4aaf732a06f7bed97db9cb36722f798ed56bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
